config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: (0..5) }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1 class="p-2 m-2 ">Todos los restaurants</h1>

  <% @restaurants.each do |restaurant| %>
    <div class="card m-3 d-flex" style="width: 18rem;">
      <p class="m-0">Restaurante: <%=restaurant.name %> </p>
      <p class="m-0">Categoria: <%=restaurant.category %> </p>
      <%= link_to "Ver detalle", restaurant_path(restaurant) %>
    </div>
  <% end %>

  <%= link_to 'agregar restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container mt-5">
<h1 class="d-flex justify-content-center">Creacion de un nuevo restaurant</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>
<%= link_to "volver", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<h1>Restaurant</h1>

<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>


<p><%= link_to 'Agregar una reseña', new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to 'Volver', restaurants_path(@restaurant) %></p>
<p><%= link_to 'Eliminar', restaurants_path(@restaurant),
        method: :delete,
        data: { confirm: "Are you sure?"} %></p>
</div>

<h2>Reviews</h2>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.content  %></p>
    <small>
      <%= link_to "eliminar", review_path(review), method: :delete, data: { confirm: "Seguro?"}  %>
    </small>
<% end %>

app/views/reviews/new.html.erb
<h1>Review <%= @restaurant.name  %></h1>

<%= simple_form_for [@restaurant, @review] do |form| %>
    <%= form.input :rating, label:"Estrellas del 1 al 5", collection: 1..5 %>
    <%= form.input :content, label:"comentario..."  %>
    <%= form.button :submit %>
<% end %>